### ISSUE TITLE
New AHRF available

### ISSUE THREAD

**Issue by olyerickson** [jjchern/ahrf#1]
Thanks for this package! It's a lifesaver.

Note that new versions of AHRF are available; you might want to update your code:

* https://datawarehouse.hrsa.gov/DataDownload/AHRF/AHRF_2015-2016.zip
* https://datawarehouse.hrsa.gov/DataDownload/AHRF/AHRF_SN_2015-2016.zip

**Comment by jjchern** [comment]
Thanks for filing the issue. The package now includes the new version of AHRF. I've also updated the two layout files and added variable labels.
